### PR TITLE
scroll on overflow for option buttons

### PR DESCRIPTION
**Pull request by vatz88**
Support for dropdown menu with scroll added.

### CODE REVIEW

**Comment by runofthemillgeek** [comment]
I see you added styles that target `.dropdown-menu`. I told you let's not mess with any bootstrap styles. Can't there be any other way to fix this? Also, could you post a pic or something that shows what exactly is the problem and how you want it to look?

**Comment by runofthemillgeek** [comment]
@VaTz88 *bump*

**Comment by vatz88** [comment]
Was going to reply from my laptop 😑

Anyway, I want it to look as it is currently i.e. buttons should not collapse and should be scrollable upon overflow.

The reason why drop-down button doesn't work is probably because of css properties `position: absolute` and `overflow-x: auto`. Both these set together create the problem. What I did is set `position: fixed` for `.dropdown-menu`. We cannot remove `overflow-x` because we need it to scroll and not collapse.

PS. Will add a image for more clarity later.

**Comment by runofthemillgeek** [comment]
I'll look into it once you post the image and if there's no other way, we'll go with the dirty fix. I just don't want to mess with BS styling whatever happens. I'm positive there's another way even if it takes extra elements.

**Comment by vatz88** [comment]
# Dropdown button works with scroll

-media-vatz88-data-github-ffcsonthego-index html

## Changes
* The add timetable button is on the side now and the dropdown works with the scroll.

## Reason for the issue
* As the CSS property `position` is changed to `fixed`  from `absolute` the dropdown will not always be exactly bellow the button. But it works well. I think it can be fixed for large screen devices by using media query as we need scroll only for small screen devices.

**Comment by vatz88** [comment]
## Issues Pending
 + [ ] Fix undesired course being deleted _Ref._  https://github.com/VaTz88/FFCSonTheGo/pull/33#issuecomment-310607995
 + [ ] Allow user to rename table

**Comment by vatz88** [comment]
@sangeeth96 merge this PR before pushing new changes.

**Comment by runofthemillgeek** [comment]
This still hasn't fixed the issues with CSS. You said yourself more CSS rules are needed to prevent issues with dropdown. 😕 I'll look for alternative solutions. In the meantime, keep the branch because if all else fails, we'll go with this.

**Comment by vatz88** [comment]
For now solve merge conflict and merge it because there are other changes as well. If you fix that issue with a better approach push the changes later.

The PR on main branch on my repo is still open. Merge the one in your repo so that the new chnages are also added to PR already open.

**Comment by vatz88** [comment]
Merge it so that I can also pull in my local repo and work on it.

**Comment by runofthemillgeek** [comment]
Why were you committing on this branch for all the other features dude? I thought this was just for the overflow thingy and I didn't notice anything else. 😕 You should've told me if you were gonna add the delete feature cos I added it to my PR. You merge my changes in the offline to your one and push it because I'm totally confused over here as to what to add and what to keep.

**Comment by runofthemillgeek** [comment]
Did you basically just pulled my `offline` branch and directly worked on it or is `sangeeth96-offline` a branch off the branch you pulled? Because I think now, it's like both of us committing on master and trying to push the changes. 😝

**Comment by vatz88** [comment]
I was pushing commits to this branch because I didn't want merge conflicts.
I was under the impression that you do get notification so you'll pull each my commit before working on your. Solve the merge conflict and merge this branch. All confusion will be gone

**Comment by runofthemillgeek** [comment]
How the heck is that supposed to be? If I had done like that on your `gh-pages` branch, it'd be in the same mess as it is right now. I branched off `gh-pages` and I'm working on it which is why everything was smooth so far. I seriously don't know how to merge the conflicts because it's a mess over here. You do it from your end (pull my changes and merge it onto your own branch). And dude, from here on out, **a PR is for a single feature**. If you are going to add more unrelated stuff, notify. 😐

**Comment by vatz88** [comment]
Yes I pulled you branch and worked on it. Both are same. So solve this branch and everything will be fine.

**Comment by vatz88** [comment]
I'll try to solve the merge conflict.
You should have merged this branch at first place.
Also keep an watch on commit and comments you would have known.

**Comment by runofthemillgeek** [comment]
It's not baba. It's like both of us working on master. Since I was under the impression that this fix was just about the overflow and that I told you I'll see to it, you shouldn't have made any further changes to this branch. If you had made any changes to `gh-pages`, I could merge them just fine on my end because my branch is rooting off of `gh-pages`. I'm not working directly off `gh-pages`. I'm completely confused and I'm positive that this is a mess right now because the conflicts have undid the changes I made.

**Comment by runofthemillgeek** [comment]
@VaTz88 Bro, I can't keep watch on every comment you put in unrelated PRs. Like I said, you should've worked on gh-pages. This is how we used to work always because you are the base and I'm the fork. When the roles reversed for just this branch, you made a mistake of directly making commits on my feature branch. Get it?

**Comment by runofthemillgeek** [comment]
@VaTz88 Resolve this from your local repo. It's safer.

**Comment by vatz88** [comment]
I'll resolve it but even if I had worked on `gh-pages` branch there would still have been a merge conflict because you pulled it before my commits.

**Comment by vatz88** [comment]
Keep pushing all changes here. I'll resolve it.
Btw we can avoid it by directly merging it in my repo and closing this PR and me making those changes again. Let's see you keep working on this branch.

**Comment by runofthemillgeek** [comment]
@VaTz88 Bhaai, that's how GitHub works. If you made changes to gh-pages, it will be my responsibility to pull those changes and that'd be totally fine. In this case, both our histories conflict. Same reason why two people don't work on the master branch.

_Sent from my Xiaomi Redmi Note 4 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Pull request closed without merging**
